apiVersion: v1
kind: Pod
metadata:
  name: loader-pod
  namespace: myproject
spec:
  volumes:
  - name: redis-storage
    persistentVolumeClaim:
     claimName: redis02
  containers:
  - image: nmolleruq/redis-perm
    name: redis-fixer
    resources:
      limits:
        cpu: 400m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi
    
    volumeMounts:
    - mountPath: /var/lib/redis/data
      name: redis-storage
    #command: ['/bin/sh', '-c', 'chown -R default:0 /var/lib/redis/data']
    # - "trap : TERM INT; sleep infinity & wait"
  restartPolicy: Never